using Azka.NotificationPlatform.Domain.Entities;
using Azka.NotificationPlatform.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Azka.NotificationPlatform.Infrastructure.Persistence.Configurations;

/// <summary>
/// EF Core Fluent API mapping for the <see cref="Notification"/> aggregate root.
/// Maps to the <c>Notifications</c> table with all domain constraints enforced at
/// the database level (column lengths, non-nullability, enum-to-int storage).
/// </summary>
internal sealed class NotificationConfiguration : IEntityTypeConfiguration<Notification>
{
    public void Configure(EntityTypeBuilder<Notification> builder)
    {
        builder.ToTable("Notifications");

        builder.HasKey(n => n.NotificationId);

        builder.Property(n => n.NotificationId)
               .ValueGeneratedNever(); // Generated by domain, not DB

        builder.Property(n => n.NotificationType)
               .IsRequired()
               .HasMaxLength(100);

        builder.Property(n => n.Recipient)
               .IsRequired()
               .HasMaxLength(320); // RFC 5321 max email address length

        builder.Property(n => n.Channel)
               .IsRequired()
               .HasConversion<int>(); // Store enum as integer

        builder.Property(n => n.Subject)
               .HasMaxLength(998); // RFC 5322 max subject length

        builder.Property(n => n.Body)
               .IsRequired()
               .HasColumnType("nvarchar(max)");

        builder.Property(n => n.Status)
               .IsRequired()
               .HasConversion<int>();

        builder.Property(n => n.CorrelationId)
               .IsRequired();

        builder.Property(n => n.RequestedAt)
               .IsRequired();

        builder.Property(n => n.ApplicationName)
               .HasMaxLength(100);

        // Unique constraint on CorrelationId — the database-level guard for FR-11
        builder.HasIndex(n => n.CorrelationId)
               .IsUnique()
               .HasDatabaseName("UX_Notifications_CorrelationId");

        // Covering index for status-based queue polling
        builder.HasIndex(n => n.Status)
               .HasDatabaseName("IX_Notifications_Status");

        builder.HasIndex(n => n.ApplicationName)
               .HasDatabaseName("IX_Notifications_ApplicationName");
    }
}
