// <auto-generated />
using System;
using Azka.NotificationPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Azka.NotificationPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260802224437_SeedNotificationTemplates")]
    partial class SeedNotificationTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Azka.NotificationPlatform.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AttemptId");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("IX_DeliveryAttempts_NotificationId");

                    b.HasIndex("NotificationId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_DeliveryAttempts_NotificationId_AttemptNumber");

                    b.ToTable("DeliveryAttempts", (string)null);
                });

            modelBuilder.Entity("Azka.NotificationPlatform.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasMaxLength(998)
                        .HasColumnType("nvarchar(998)");

                    b.HasKey("NotificationId");

                    b.HasIndex("ApplicationName")
                        .HasDatabaseName("IX_Notifications_ApplicationName");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("UX_Notifications_CorrelationId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Notifications_Status");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Azka.NotificationPlatform.Domain.Entities.NotificationHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("NotificationId", "ChangedAt")
                        .HasDatabaseName("IX_NotificationHistories_NotificationId_ChangedAt");

                    b.ToTable("NotificationHistories", (string)null);
                });

            modelBuilder.Entity("Azka.NotificationPlatform.Domain.Entities.NotificationProvider", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ProviderId");

                    b.HasIndex("ProviderName")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationProviders_ProviderName");

                    b.HasIndex("Channel", "IsActive")
                        .HasDatabaseName("IX_NotificationProviders_Channel_IsActive");

                    b.ToTable("NotificationProviders", (string)null);

                    b.HasData(
                        new
                        {
                            ProviderId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Channel = 0,
                            IsActive = true,
                            ProviderName = "SendGrid"
                        },
                        new
                        {
                            ProviderId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Channel = 1,
                            IsActive = true,
                            ProviderName = "Twilio"
                        },
                        new
                        {
                            ProviderId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Channel = 2,
                            IsActive = true,
                            ProviderName = "Firebase"
                        });
                });

            modelBuilder.Entity("Azka.NotificationPlatform.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subject")
                        .HasMaxLength(998)
                        .HasColumnType("nvarchar(998)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("TemplateId");

                    b.HasIndex("Channel", "Language", "Status", "Version")
                        .HasDatabaseName("IX_NotificationTemplates_Channel_Language_Status_Version");

                    b.ToTable("NotificationTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            TemplateId = new Guid("19b318e2-d938-4279-b892-12807759c9dd"),
                            Body = "<h2>Welcome to Azka!</h2><p>Your account has been successfully created. You can now log in and start using the platform.</p><p>If you have any questions, our support team is always here to help.</p><br/><p>Best regards,<br/><strong>Azka Platform Team</strong></p>",
                            Channel = 0,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Welcome to Azka Platform!",
                            TemplateName = "UserRegistration",
                            Version = 2
                        },
                        new
                        {
                            TemplateId = new Guid("a2534032-029e-4900-bb6d-435216e776f6"),
                            Body = "Welcome to Azka Platform! Your account is ready. Log in at azka.io to get started.",
                            Channel = 1,
                            Language = "en-US",
                            Status = "Active",
                            TemplateName = "UserRegistration",
                            Version = 2
                        },
                        new
                        {
                            TemplateId = new Guid("db4ad581-a1fb-4742-b7ee-f0e7f37f7365"),
                            Body = "Welcome to Azka Platform! Tap to open your profile and get started.",
                            Channel = 2,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Welcome to Azka!",
                            TemplateName = "UserRegistration",
                            Version = 2
                        },
                        new
                        {
                            TemplateId = new Guid("a27ec50b-bf99-4d61-8b9f-8dbcbe3a97ce"),
                            Body = "<h2>Password Reset</h2><p>We received a request to reset the password on your Azka account.</p><p>Please follow the instructions in your account portal to complete the reset. This link is valid for 15 minutes.</p><p>If you did not request this, you can safely ignore this email.</p><br/><p>Regards,<br/><strong>Azka Security Team</strong></p>",
                            Channel = 0,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Password Reset Request ? Azka Platform",
                            TemplateName = "PasswordReset",
                            Version = 2
                        },
                        new
                        {
                            TemplateId = new Guid("f59d2754-2b8e-428f-8bf5-252bff6c4559"),
                            Body = "Azka: A password reset was requested for your account. Visit the platform to complete the process. Valid for 15 minutes.",
                            Channel = 1,
                            Language = "en-US",
                            Status = "Active",
                            TemplateName = "PasswordReset",
                            Version = 2
                        },
                        new
                        {
                            TemplateId = new Guid("d63ba317-1c20-418b-8a32-a11616ec25cf"),
                            Body = "A password reset was requested for your account. Tap to verify.",
                            Channel = 2,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Password Reset Requested",
                            TemplateName = "PasswordReset",
                            Version = 2
                        },
                        new
                        {
                            TemplateId = new Guid("47b149ec-1319-44f0-85b1-f1556d8f94f7"),
                            Body = "<h2>Order Confirmed!</h2><p>Thank you for your order. We have received it and it is now being processed.</p><p>You will receive a follow-up notification once your order has been dispatched.</p><br/><p>Thank you for choosing Azka.<br/><strong>Azka Order Team</strong></p>",
                            Channel = 0,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Your Order Has Been Confirmed ? Azka",
                            TemplateName = "OrderConfirmation",
                            Version = 2
                        },
                        new
                        {
                            TemplateId = new Guid("b3919f3a-95f4-4d5f-b84e-8146c75f8b17"),
                            Body = "Azka: Your order has been confirmed and is now being processed. Thank you for your purchase!",
                            Channel = 1,
                            Language = "en-US",
                            Status = "Active",
                            TemplateName = "OrderConfirmation",
                            Version = 2
                        },
                        new
                        {
                            TemplateId = new Guid("c57a5edd-54ed-4ae5-b9da-b41c867ba939"),
                            Body = "<h2 style=\"color:red;\">System Alert</h2><p>A critical system event has been detected on the Azka platform. Please log in to the administration panel immediately to review and take action.</p><p>This is an automated alert from the Azka monitoring system.</p>",
                            Channel = 0,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "SYSTEM ALERT ? Azka Platform",
                            TemplateName = "SystemAlert",
                            Version = 2
                        },
                        new
                        {
                            TemplateId = new Guid("f467354c-834e-48a7-8dc1-ec7b58f5c2a8"),
                            Body = "<h2>Payment Successful</h2><p>Hi there,</p><p>We've successfully processed your payment of <strong>{{Amount}}</strong> for invoice <strong>{{InvoiceNumber}}</strong>.</p><p>Thank you for your business!</p><p>Best regards,<br/><strong>Azka Finance Team</strong></p>",
                            Channel = 0,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Payment Confirmed - Thank You",
                            TemplateName = "PaymentConfirmation",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("8836c121-4384-4e72-b764-f60783aa0cef"),
                            Body = "Azka: Payment of {{Amount}} for invoice {{InvoiceNumber}} was successful. Thank you!",
                            Channel = 1,
                            Language = "en-US",
                            Status = "Active",
                            TemplateName = "PaymentConfirmation",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("9f1f5b65-d655-42aa-b7f0-e6992ff7ddfe"),
                            Body = "Your payment of {{Amount}} has been processed successfully.",
                            Channel = 2,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Payment Confirmed",
                            TemplateName = "PaymentConfirmation",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("8474d34b-ba0e-4cac-9973-b94dc13fb5b5"),
                            Body = "<h2>Transaction Failure Alert</h2><p>Dear customer,</p><p>We attempted to process a transaction for your account, but it failed. Reference: <strong>{{TransactionId}}</strong>. Reason: {{FailureReason}}.</p><p>Please update your payment method or try again.</p><p>Regards,<br/><strong>Azka Support Team</strong></p>",
                            Channel = 0,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Transaction Failed - Action Required",
                            TemplateName = "TransactionFailure",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("d22c639f-2d58-4236-a012-a7d49f17b5a7"),
                            Body = "Azka: Transaction {{TransactionId}} failed. Reason: {{FailureReason}}. Please check your account.",
                            Channel = 1,
                            Language = "en-US",
                            Status = "Active",
                            TemplateName = "TransactionFailure",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("e3f885e3-c6df-470f-a156-0d5c7b5d2c3f"),
                            Body = "Transaction of {{Amount}} failed. Tap to review.",
                            Channel = 2,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Transaction Failed",
                            TemplateName = "TransactionFailure",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("6caa04e4-0cf0-484a-ab07-c3fc379be45a"),
                            Body = "<h2>Service Interruption Notice</h2><p>Hello,</p><p>We are experiencing a temporary service interruption affecting <strong>{{AffectedService}}</strong>. Our team is actively investigating, and we expect resolution by <strong>{{EstimatedResolution}}</strong>.</p><p>We apologize for the inconvenience.</p><p>Sincerely,<br/><strong>Azka Operations Team</strong></p>",
                            Channel = 0,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Service Interruption Notice",
                            TemplateName = "ServiceInterruption",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("6f0a094e-01df-4301-aa61-0dc56964dc76"),
                            Body = "Azka Alert: Temporary service interruption affecting {{AffectedService}}. Expected resolution: {{EstimatedResolution}}. We apologize for the inconvenience.",
                            Channel = 1,
                            Language = "en-US",
                            Status = "Active",
                            TemplateName = "ServiceInterruption",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("532f0b36-8034-4258-a04b-31b3036d8eb7"),
                            Body = "Service interruption detected for {{AffectedService}}. Tap for updates.",
                            Channel = 2,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Service Interruption",
                            TemplateName = "ServiceInterruption",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("cc94d662-a814-4d22-998f-db2251523c75"),
                            Body = "<h2>Your OTP</h2><p>Hello,</p><p>Your one-time password is: <strong style='font-size:24px; letter-spacing:2px; color:#0056b3;'>{{OTP}}</strong></p><p>This code is valid for 5 minutes. Do not share this code with anyone.</p><p>Best regards,<br/><strong>Azka Security Team</strong></p>",
                            Channel = 0,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Your One-Time Password (OTP) - Azka",
                            TemplateName = "OTP",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("f8d8afff-e0b0-4a92-83e0-883f45b108b1"),
                            Body = "Azka: Your verification code is {{OTP}}. Valid for 5 minutes. Do not share this code.",
                            Channel = 1,
                            Language = "en-US",
                            Status = "Active",
                            TemplateName = "OTP",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("2fe49b2e-ddce-4096-aa40-8b88dbba57b9"),
                            Body = "Your verification code is {{OTP}}. Valid for 5 minutes.",
                            Channel = 2,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Verification Code",
                            TemplateName = "OTP",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("49ffb717-49b1-47b5-a06e-f5bb50744795"),
                            Body = "<h2>Appointment Confirmation</h2><p>Dear customer,</p><p>A maintenance appointment has been scheduled for <strong>{{AppointmentDate}}</strong> at <strong>{{AppointmentTime}}</strong>.</p><p>Our technician, <strong>{{TechnicianName}}</strong>, will visit your address.</p><p>Best regards,<br/><strong>Azka Maintenance Team</strong></p>",
                            Channel = 0,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Maintenance Appointment Scheduled",
                            TemplateName = "MaintenanceAppointment",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("730cea46-535d-4795-9c99-e8c5d1ed982c"),
                            Body = "Azka: Maintenance appointment scheduled for {{AppointmentDate}} at {{AppointmentTime}} with {{TechnicianName}}. Reply to reschedule.",
                            Channel = 1,
                            Language = "en-US",
                            Status = "Active",
                            TemplateName = "MaintenanceAppointment",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("98a41d3f-71cf-4753-a865-398d04fc4d6c"),
                            Body = "Maintenance scheduled on {{AppointmentDate}} at {{AppointmentTime}}. Tap for details.",
                            Channel = 2,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Appointment Scheduled",
                            TemplateName = "MaintenanceAppointment",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("7a94c765-c2b2-429e-9d4c-e15281158352"),
                            Body = "<h2>Meter Reading Reminder</h2><p>Hello,</p><p>It is time to submit your meter reading for account <strong>{{AccountNumber}}</strong>. Please submit it by <strong>{{DueDate}}</strong> to ensure accurate billing.</p><p>Best regards,<br/><strong>Azka Billing Team</strong></p>",
                            Channel = 0,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Reminder: Submit Your Meter Reading",
                            TemplateName = "MeterReadingReminder",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("d147a76d-11ca-4f1e-81a7-42656adf0b0b"),
                            Body = "Azka Reminder: Please submit your meter reading for account {{AccountNumber}} by {{DueDate}}. Visit azka.io/meter.",
                            Channel = 1,
                            Language = "en-US",
                            Status = "Active",
                            TemplateName = "MeterReadingReminder",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("1b3038b9-9fbf-41c5-8748-40cbf3d2c605"),
                            Body = "Please submit your meter reading for account {{AccountNumber}} by {{DueDate}}. Tap to submit.",
                            Channel = 2,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Meter Reading Due",
                            TemplateName = "MeterReadingReminder",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("877d008b-4188-4f37-8780-72bd7f845aa7"),
                            Body = "<h2>New Invoice Ready</h2><p>Dear customer,</p><p>A new invoice <strong>{{InvoiceNumber}}</strong> has been generated for your account. Amount due: <strong>{{Amount}}</strong>. Due date: <strong>{{DueDate}}</strong>.</p><p>Please log in to your portal to pay.</p><p>Best regards,<br/><strong>Azka Billing Team</strong></p>",
                            Channel = 0,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "New Invoice Generated - {{InvoiceNumber}}",
                            TemplateName = "InvoiceGeneration",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("1b8b55e3-5032-4715-937b-80c16267ee5f"),
                            Body = "Azka: New invoice {{InvoiceNumber}} generated. Amount: {{Amount}} due on {{DueDate}}. Visit azka.io/invoices to pay.",
                            Channel = 1,
                            Language = "en-US",
                            Status = "Active",
                            TemplateName = "InvoiceGeneration",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("e926f5a9-3c12-48a8-9668-3841d0fc4739"),
                            Body = "Invoice {{InvoiceNumber}} for {{Amount}} is now available. Due date: {{DueDate}}. Tap to view.",
                            Channel = 2,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "New Invoice Available",
                            TemplateName = "InvoiceGeneration",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("8bfe1266-0ab8-4b6e-8da5-f052db823a1c"),
                            Body = "<h2>Support Ticket Update</h2><p>Hello,</p><p>Your support ticket <strong>#{{TicketId}}</strong> has been updated.</p><p><strong>Latest Update:</strong><br/>{{TicketUpdate}}</p><p>View full history or reply in your support portal.</p><p>Best regards,<br/><strong>Azka Customer Support</strong></p>",
                            Channel = 0,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Support Ticket Updated - #{{TicketId}}",
                            TemplateName = "SupportTicketUpdate",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("6902fe8b-8159-4da6-a090-76a0853d67a9"),
                            Body = "Azka: Ticket #{{TicketId}} has been updated. Update: {{TicketUpdate}}. Visit portal for details.",
                            Channel = 1,
                            Language = "en-US",
                            Status = "Active",
                            TemplateName = "SupportTicketUpdate",
                            Version = 1
                        },
                        new
                        {
                            TemplateId = new Guid("8b3168ba-b25d-4a2c-97a1-269a67a11dec"),
                            Body = "Ticket #{{TicketId}} was updated: '{{TicketUpdate}}'. Tap to view.",
                            Channel = 2,
                            Language = "en-US",
                            Status = "Active",
                            Subject = "Support Ticket Update",
                            TemplateName = "SupportTicketUpdate",
                            Version = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
