// <auto-generated />
using System;
using Azka.NotificationPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Azka.NotificationPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Azka.NotificationPlatform.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AttemptId");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("IX_DeliveryAttempts_NotificationId");

                    b.HasIndex("NotificationId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_DeliveryAttempts_NotificationId_AttemptNumber");

                    b.ToTable("DeliveryAttempts", (string)null);
                });

            modelBuilder.Entity("Azka.NotificationPlatform.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasMaxLength(998)
                        .HasColumnType("nvarchar(998)");

                    b.HasKey("NotificationId");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("UX_Notifications_CorrelationId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Notifications_Status");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Azka.NotificationPlatform.Domain.Entities.NotificationHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("NotificationId", "ChangedAt")
                        .HasDatabaseName("IX_NotificationHistories_NotificationId_ChangedAt");

                    b.ToTable("NotificationHistories", (string)null);
                });

            modelBuilder.Entity("Azka.NotificationPlatform.Domain.Entities.NotificationProvider", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ProviderId");

                    b.HasIndex("ProviderName")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationProviders_ProviderName");

                    b.HasIndex("Channel", "IsActive")
                        .HasDatabaseName("IX_NotificationProviders_Channel_IsActive");

                    b.ToTable("NotificationProviders", (string)null);
                });

            modelBuilder.Entity("Azka.NotificationPlatform.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subject")
                        .HasMaxLength(998)
                        .HasColumnType("nvarchar(998)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("TemplateId");

                    b.HasIndex("Channel", "Language", "Status", "Version")
                        .HasDatabaseName("IX_NotificationTemplates_Channel_Language_Status_Version");

                    b.ToTable("NotificationTemplates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
