using Azka.NotificationPlatform.Domain.Enums;

namespace Azka.NotificationPlatform.Domain.Entities;

/// <summary>
/// Aggregate root representing a single notification request raised by any upstream
/// system within the Azka platform.
/// </summary>
/// <remarks>
/// A <see cref="Notification"/> is the central aggregate of the domain. It owns its
/// delivery lifecycle through <see cref="NotificationStatus"/> and references child
/// <see cref="DeliveryAttempt"/> records. The <see cref="CorrelationId"/> field supports
/// idempotent intake (FR-11 Duplicate Prevention): callers must supply a stable, unique
/// key so the platform can detect and reject duplicate submissions at the application layer
/// without needing to compare payload content.
/// </remarks>
public sealed class Notification
{
    /// <summary>
    /// Primary surrogate key for the notification record. Generated by the platform
    /// at intake time using <see cref="Guid.NewGuid"/>.
    /// </summary>
    public Guid NotificationId { get; init; }

    /// <summary>
    /// A short, human-readable label that categorises the notification by its
    /// business purpose (e.g., "OrderConfirmation", "PasswordReset", "AlertCritical").
    /// Used for template resolution and analytics bucketing.
    /// </summary>
    public string NotificationType { get; private set; }

    /// <summary>
    /// The delivery address of the intended recipient in a format appropriate for the
    /// selected <see cref="Channel"/> — e.g., an RFC 5321 email address for
    /// <see cref="NotificationChannel.Email"/>, an E.164 phone number for
    /// <see cref="NotificationChannel.SMS"/>, or a device/topic token for
    /// <see cref="NotificationChannel.Push"/>.
    /// </summary>
    public string Recipient { get; private set; }

    /// <summary>
    /// The delivery channel through which the notification must be dispatched.
    /// </summary>
    public NotificationChannel Channel { get; private set; }

    /// <summary>
    /// The message subject line. Meaningful for <see cref="NotificationChannel.Email"/>
    /// and optionally for <see cref="NotificationChannel.Push"/> title payloads.
    /// May be <see langword="null"/> for SMS where no subject concept exists.
    /// </summary>
    public string? Subject { get; private set; }

    /// <summary>
    /// The full message body. For email this is the rendered HTML or plain-text content;
    /// for SMS, the raw text; for push, the notification body string.
    /// </summary>
    public string Body { get; private set; }

    /// <summary>
    /// Current lifecycle state of this notification. Starts as
    /// <see cref="NotificationStatus.Pending"/> and is advanced by the application layer
    /// as the notification progresses through the pipeline.
    /// </summary>
    public NotificationStatus Status { get; private set; }

    /// <summary>
    /// Caller-supplied idempotency key (FR-11 Duplicate Prevention).
    /// Upstream systems MUST send a stable value (e.g., a UUID they generate once)
    /// so the platform can detect retried requests and avoid duplicate deliveries.
    /// The application layer is responsible for enforcing uniqueness against a durable
    /// store before persisting a new <see cref="Notification"/>.
    /// </summary>
    public Guid CorrelationId { get; init; }

    /// <summary>
    /// UTC timestamp at which the upstream system submitted this notification request.
    /// Distinct from any persistence timestamp; this reflects business-level intent time.
    /// </summary>
    public DateTime RequestedAt { get; init; }

    // -------------------------------------------------------------------------
    // Construction
    // -------------------------------------------------------------------------

    /// <summary>
    /// Initialises a new <see cref="Notification"/> in the
    /// <see cref="NotificationStatus.Pending"/> state.
    /// </summary>
    /// <param name="notificationId">Platform-generated surrogate key.</param>
    /// <param name="notificationType">Business type label.</param>
    /// <param name="recipient">Delivery address appropriate for the chosen channel.</param>
    /// <param name="channel">Target delivery channel.</param>
    /// <param name="body">Rendered message body.</param>
    /// <param name="correlationId">Caller-supplied idempotency key.</param>
    /// <param name="requestedAt">UTC time the request was raised by the caller.</param>
    /// <param name="subject">Optional subject line (required for Email).</param>
    public Notification(
        Guid notificationId,
        string notificationType,
        string recipient,
        NotificationChannel channel,
        string body,
        Guid correlationId,
        DateTime requestedAt,
        string? subject = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(notificationType, nameof(notificationType));
        ArgumentException.ThrowIfNullOrWhiteSpace(recipient, nameof(recipient));
        ArgumentException.ThrowIfNullOrWhiteSpace(body, nameof(body));

        NotificationId   = notificationId == Guid.Empty ? throw new ArgumentException("NotificationId must not be an empty GUID.", nameof(notificationId)) : notificationId;
        CorrelationId    = correlationId  == Guid.Empty ? throw new ArgumentException("CorrelationId must not be an empty GUID.",  nameof(correlationId))  : correlationId;
        NotificationType = notificationType;
        Recipient        = recipient;
        Channel          = channel;
        Subject          = subject;
        Body             = body;
        Status           = NotificationStatus.Pending;
        RequestedAt      = requestedAt;
    }

    // -------------------------------------------------------------------------
    // Domain behaviour — state transitions
    // -------------------------------------------------------------------------

    /// <summary>Advances the status to <see cref="NotificationStatus.Queued"/>.</summary>
    /// <exception cref="InvalidOperationException">
    /// Thrown when the current status does not allow queuing (only Pending → Queued is valid).
    /// </exception>
    public void MarkAsQueued()
    {
        EnsureStatus(NotificationStatus.Pending, "Only a Pending notification can be queued.");
        Status = NotificationStatus.Queued;
    }

    /// <summary>Advances the status to <see cref="NotificationStatus.Processing"/>.</summary>
    public void MarkAsProcessing()
    {
        EnsureStatus(NotificationStatus.Queued, "Only a Queued notification can be marked as Processing.");
        Status = NotificationStatus.Processing;
    }

    /// <summary>Advances the status to <see cref="NotificationStatus.Delivered"/>.</summary>
    public void MarkAsDelivered()
    {
        EnsureStatus(NotificationStatus.Processing, "Only a Processing notification can be marked as Delivered.");
        Status = NotificationStatus.Delivered;
    }

    /// <summary>Advances the status to <see cref="NotificationStatus.Failed"/>.</summary>
    public void MarkAsFailed()
    {
        EnsureStatus(NotificationStatus.Processing, "Only a Processing notification can be marked as Failed.");
        Status = NotificationStatus.Failed;
    }

    /// <summary>
    /// Marks the notification as <see cref="NotificationStatus.Cancelled"/>.
    /// Valid from any non-terminal state (Pending or Queued).
    /// </summary>
    public void Cancel()
    {
        if (Status is NotificationStatus.Delivered
                   or NotificationStatus.Failed
                   or NotificationStatus.Cancelled)
        {
            throw new InvalidOperationException(
                $"Cannot cancel a notification that is already in a terminal state ({Status}).");
        }

        Status = NotificationStatus.Cancelled;
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    private void EnsureStatus(NotificationStatus required, string message)
    {
        if (Status != required)
            throw new InvalidOperationException(message);
    }
}
